import "./globals.css";

import type { Metadata } from "next";
import { Scope_One } from "next/font/google";

import { ChangeContentProvider } from "@/contexts/change-content-context";
import { ThemeTogglerProvider } from "@/contexts/theme-toggler-content";

const scopeOne = Scope_One({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${scopeOne.className} antialiased`}>
        <ThemeTogglerProvider>
          <ChangeContentProvider>{children}</ChangeContentProvider>
        </ThemeTogglerProvider>
      </body>
    </html>
  );
}
