import "./globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { ClientsProvider } from "@/contexts/clients-context";
import { SearchClientsByNameProvider } from "@/contexts/search-clients-by-name-context";
import { ThemeTogglerProvider } from "@/contexts/theme-toggler-content";

import { Providers } from "../components/providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Providers>
          <ClientsProvider>
            <SearchClientsByNameProvider>
              <ThemeTogglerProvider>{children}</ThemeTogglerProvider>
            </SearchClientsByNameProvider>
          </ClientsProvider>
        </Providers>
      </body>
    </html>
  );
}
